#!/sbin/sh

BDEV=`/sbin/busybox readlink /dev/block/platform/msm_sdcc.1/by-name/userdata`
FSTYPE=`/sbin/busybox blkid $BDEV | /sbin/busybox cut -d ' ' -f3 | /sbin/busybox cut -d '"' -f2`
METADATA='ls /dev/block/platform/msm_sdcc.1/by-name/ | grep "metadata"'

if [ "$FSTYPE" == "ext4" ]
then
  sed -i '/data/s/f2fs/ext4/g' /etc/recovery.fstab;
  sed -i '/data/s/f2fs/ext4/g' /etc/twrp.fstab;
  if [ "$METADATA" == "metadata" ] # Metadata is present
  then
  sed -i '/data/s/fsflags="inline_xattr";length=-16384/encryptable=\/dev\/block\/platform\/msm_sdcc.1\/by-name\/metadata/g' /etc/recovery.fstab;
  sed -i '/data/s/fsflags="inline_xattr";length=-16384/encryptable=\/dev\/block\/platform\/msm_sdcc.1\/by-name\/metadata/g' /etc/twrp.fstab;
  else
  sed -i '/data/s/fsflags="inline_xattr";//g' /etc/recovery.fstab;
  sed -i '/data/s/fsflags="inline_xattr";//g' /etc/twrp.fstab;
  fi
else
  echo '# GPE CHECKED' >> /etc/recovery.fstab;
  echo '# GPE CHECKED' >> /etc/twrp.fstab;
  echo '' >> /etc/recovery.fstab;
  echo '' >> /etc/twrp.fstab;
fi
